yaml
name: ZPlatform NodeJS CI


on:
  push:
    branches:
      - main
      - user-account-management
  pull_request:
    branches:
      - main


jobs:
  build:


    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Run npm 
      run: npm
    - name: Run tests
      run: npm run test